CC        := gcc
WARNFLAGS := -Wall

ifeq ($(strip $(debug)),yes)
DBGFLAGS := -g3 -D__DEBUG__ -D__TRACE_CHECK__
OPTFLAGS := -O0
else
OPTFLAGS := -O2
endif

INCDIRS  := ..

CFLAGS   := $(WARNFLAGS) $(DBGFLAGS) $(OPTFLAGS) $(foreach d,$(INCDIRS),-I$(d))

SOURCES := trace.c simple-filter.c parser.c
OBJECTS := $(patsubst %.c,%.o,$(SOURCES))

all: libtrace.a
	$(MAKE) debug=$(debug) -C test $@

libtrace.a: libtrace.a($(OBJECTS))

%.o: %.c
	$(CC) -c $(CFLAGS) $<

%.E: %.c
	$(CC) -E $(CFLAGS) $< -o $@

clean:
	rm -f *.o *~ *.a
	$(MAKE) -C test $@	
	